apiVersion: v1
kind: Service
metadata:
  name: user-creation-service
spec:
  selector:
    app: user-creation-service
  type: ClusterIP
  ports:
    - name: user-creation-service
      port: 9000
      targetPort: 9000
      protocol: TCP
